export class sprintReport{
    teamID:string
    sprintNum:number;
    sprintStartdate:string; 
    sprintEnddate:string; 
    scrumMasterEmail:string;
    planned_PBI_Completed:number;
    planned_PBI_NotCompleted:number;
    plannedBugCompleted:number;
    plannedBugNotCompleted:number;
    Addon_PBI_Completed:number;
    Addon_PBI_NotCompleted:number;
    AddonBugCompleted:number;
    AddonBugNotCompleted:number;
    reason1:string;
    reason2:string;
    reason3:string;
    reason4:string;
    reason5:string;
    reasonOther:string;
    supportPBI:number;
    supportBug:number;
    newValuePBI:number;
    newValueBug:number;
    improvementPBI:number;
    improvementBug:number;
    sprintCapacity:number;
    plannedCapacity:number;
    actualCapacity:number;
    estimatedHours:number;
    completedHours:number;
    createDate:string;
    lastUpdDate:string;

    constructor(team_id:number,
        teamID:string,
        sprintNum:number,
        sprintStartdate:string, 
        sprintEnddate:string,
        scrumMasterEmail:string,
        planned_PBI_Completed:number,
        planned_PBI_NotCompleted:number,
        plannedBugCompleted:number,
        plannedBugNotCompleted:number,
        Addon_PBI_Completed:number,
        Addon_PBI_NotCompleted:number,
        AddonBugCompleted:number,
        AddonBugNotCompleted:number,
        reason1:string,
        reason2:string,
        reason3:string,
        reason4:string,
        reason5:string,
        reasonOther:string,
        supportPBI:number,
        supportBug:number,
        newValuePBI:number,
        newValueBug:number,
        improvementPBI:number,
        improvementBug:number,
        sprintCapacity:number,
        plannedCapacity:number,
        actualCapacity:number,
        estimatedHours:number,
        completedHours:number,
        createDate:string,
        lastUpdDate:string){
        this.teamID=teamID
        this.sprintNum=sprintNum;
        this.sprintStartdate=sprintStartdate;
        this.sprintEnddate=sprintEnddate;
        this.scrumMasterEmail=scrumMasterEmail;
        this.planned_PBI_Completed=planned_PBI_Completed
        this.planned_PBI_NotCompleted=planned_PBI_NotCompleted;
        this.plannedBugCompleted=plannedBugCompleted;
        this.plannedBugNotCompleted=plannedBugNotCompleted;
        this.Addon_PBI_Completed=Addon_PBI_Completed;
        this.Addon_PBI_NotCompleted=Addon_PBI_NotCompleted;
        this.AddonBugCompleted=AddonBugCompleted;
        this.AddonBugNotCompleted=AddonBugNotCompleted;
        this.reason1=reason1; 
        this.reason2=reason2;
        this.reason3=reason3;
        this.reason4=reason4;
        this.reason5=reason5;
        this.reasonOther=reasonOther;
        this.supportPBI=supportPBI;
        this.supportBug=supportBug;
        this.newValuePBI=newValuePBI;
        this.newValueBug=newValueBug;
        this.improvementPBI=improvementPBI;
        this.improvementBug=improvementBug;
        this.sprintCapacity=sprintCapacity; 
        this.plannedCapacity=plannedCapacity;
        this.actualCapacity=actualCapacity;
        this.estimatedHours=estimatedHours;
        this.completedHours=completedHours;
        this.createDate=createDate;
        this.lastUpdDate=lastUpdDate;
    }
}